# Generated by Django 4.2.6 on 2023-10-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('identification', models.CharField(max_length=10, verbose_name='Identificacion')),
                ('date_exam', models.DateField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('exam_url', models.CharField(max_length=500, verbose_name='Url-PDF')),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pat_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pat_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen Paciente',
                'verbose_name_plural': 'Examenes de Pacientes',
                'ordering': ('date_exam',),
            },
        ),
    ]
