# Generated by Django 4.2.6 on 2023-10-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_typeexam_create_by_alter_typeexam_update_by'),
        ('company', '0004_alter_membership_create_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('identification', models.CharField(max_length=10, unique=True, verbose_name='Identificacion')),
                ('date_exam', models.DateField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Empresa')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pat_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pat_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='patientexam',
            options={'ordering': ('id',), 'verbose_name': 'Paciente Examen', 'verbose_name_plural': 'Examenes del Pacientes'},
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='company',
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='date_exam',
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='patientexam',
            name='identification',
        ),
        migrations.AddField(
            model_name='patientexam',
            name='date_time_exam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientexam',
            name='type_exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exam.typeexam', verbose_name='Tipo Examen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientexam',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patex_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientexam',
            name='exam_url',
            field=models.CharField(max_length=5000, verbose_name='Url-PDF'),
        ),
        migrations.AlterField(
            model_name='patientexam',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patex_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientExamSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_folder_sample', models.CharField(max_length=5000, verbose_name='Url-Muestra PNG')),
                ('sample_url', models.CharField(max_length=5000, verbose_name='Url-Muestra PNG')),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patexmt_create_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient', verbose_name='Paciente')),
                ('patientexam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patientexam', verbose_name='Muestras del Paciente')),
                ('type_exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.typeexam', verbose_name='Tipo Examen')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patexmt_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientexam',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patient.patient', verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
