# Generated by Django 4.2.6 on 2023-10-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_alter_patientexam_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_exam',
        ),
    ]
