# Generated by Django 4.2.6 on 2023-10-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientexam_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientexam',
            name='exam_url',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Url-PDF'),
        ),
    ]
