# Generated by Django 4.2.6 on 2023-10-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patientexam_exam_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientexam',
            name='date_time_exam',
        ),
        migrations.AddField(
            model_name='patientexam',
            name='date_exam',
            field=models.DateField(blank=True, null=True),
        ),
    ]
