# Generated by Django 4.2.6 on 2023-10-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_typeexam_create_by_alter_typeexam_update_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0006_remove_patientexam_date_time_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_folder_sample', models.CharField(max_length=5000, verbose_name='Url-Muestra PNG')),
                ('sample_url', models.CharField(max_length=5000, verbose_name='Url-Muestra PNG')),
                ('save_date', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patexmt_create_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient', verbose_name='Paciente')),
                ('patientexam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patientexam', verbose_name='Muestras del Paciente')),
                ('type_exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.typeexam', verbose_name='Tipo Examen')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patexmt_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientExamSample',
        ),
    ]
