# Generated by Django 4.2.6 on 2023-10-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_examsample_delete_patientexamsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsample',
            name='name',
            field=models.CharField(default=1, max_length=1000, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
