# Generated by Django 4.2.6 on 2023-10-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_membership_create_by_and_more'),
        ('patient', '0008_examsample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsample',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Compania'),
            preserve_default=False,
        ),
    ]
