# Generated by Django 4.2.6 on 2023-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_examsample_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsample',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
