# Generated by Django 4.2.6 on 2023-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_examsample_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsample',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Diagnostico'),
        ),
    ]
