# Generated by Django 4.2.6 on 2023-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_examsample_sample_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsample',
            name='diagnostic',
            field=models.CharField(blank=True, default='', max_length=2500, null=True, verbose_name='Diagnostico'),
        ),
    ]
