# Generated by Django 4.2.6 on 2023-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_examsample_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientexam',
            name='diagnostic_general',
            field=models.CharField(blank=True, default='', max_length=2500, null=True, verbose_name='Diagnostico General'),
        ),
    ]
