# Generated by Django 4.2.6 on 2023-11-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_patientexam_diagnostic_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.CharField(max_length=10, verbose_name='Identificacion'),
        ),
    ]
