# Generated by Django 4.2.6 on 2023-10-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=10000)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('connections', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mepb_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mebp_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
                'ordering': ('cost',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('identification', models.CharField(max_length=13, verbose_name='Identificacion')),
                ('identification_type', models.CharField(choices=[('CI', 'CI'), ('PASS', 'PASAPORTE'), ('RUC', 'RUC')], max_length=10, verbose_name='Tipo Identificacion')),
                ('phone', models.CharField(max_length=10, verbose_name='Celular/Telefono')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('registration_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('pay_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('court_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Corte')),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_create_by', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Membresia', to='company.membership', verbose_name='Membresia')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_update_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario - Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('id', 'registration_date'),
            },
        ),
    ]
