# Generated by Django 4.2.6 on 2023-11-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_logo_company_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='url',
            new_name='logo',
        ),
    ]
