# Generated by Django 4.2.6 on 2023-12-29 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0018_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('date_creation', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coun_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coun_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ('name',),
            },
        ),
    ]
