# Generated by Django 4.2.6 on 2023-12-29 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='provincie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Provincia', to='company.province', verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
