# Generated by Django 4.2.6 on 2023-12-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Pais_Ciudad', to='company.country', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='city',
            name='provincie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Provincia_Ciudad', to='company.province', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Pais_Provincia', to='company.country', verbose_name='Pais'),
        ),
    ]
