# Generated by Django 4.2.6 on 2024-01-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_city_country_alter_city_provincie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='provincie',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
